### ISSUE TITLE
Unable to set settings.ini

### ISSUE THREAD

**Issue by plaidshirtakos** [CMiksche/gitea-auto-update#10]
**Describe the bug**
I got following error message: ~$ ```
gitea-auto-update --settings=/home/kovacsa/settings.ini
Traceback (most recent call last):
  File "/usr/local/bin/gitea-auto-update", line 11, in <module>
    load_entry_point('gitea-auto-update==2.0.5', 'console_scripts', 'gitea-auto-update')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/gitea_auto_update/update.py", line 14, in <module>
    import gitea_auto_update.lib.download
  File "/usr/local/lib/python2.7/dist-packages/gitea_auto_update/lib/download.py", line 12, in <module>
    from shutil import which    # from whichcraft import which
ImportError: cannot import name which
```

**To Reproduce**
Steps to reproduce the behavior:
I issued `gitea-auto-update --settings=/home/kovacsa/settings.ini` command to set location of settings file.

**Comment by CMiksche** [comment]
> File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 480, in load_entry_point

This project only runs with python 3, you try to use it with python 2. 
You can make sure you run this with python 3 by using the following command:  `pip3 install gitea-auto-update`. (You should uninstall gitea-auto-update before that with `pip uninstall gitea-auto-update`)

I will add a restriction for python 3 to the setup progress and document the requirement in the README.md.
