### ISSUE TITLE
[LXC] Update fails: Permission denied

### ISSUE THREAD

**Issue by BadCo-NZ** [CMiksche/gitea-auto-update#27]
**Describe the bug**
I am getting a permission denied error when trying to run this inside TurnkeyLinux Gitea LXC.

https://www.turnkeylinux.org/gitea

**To Reproduce**
```
root@gitea ~# gitea-auto-update --settings=/home/git/update/settings.ini
/bin/sh: 1: /home/git/: Permission denied
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/lib/version.py", line 48, in get_current_version
    current_version = self.get_version_from_file()
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/lib/version.py", line 42, in get_version_from_file
    return parse_file_version(version_string)
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/lib/version.py", line 24, in parse_file_version
    return string.split(" ")[2]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gitea-auto-update", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/update.py", line 90, in main
    fire.Fire(updater)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/update.py", line 83, in updater
    Update(config)
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/update.py", line 35, in __init__
    self.check_and_update()
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/update.py", line 62, in check_and_update
    current_version = version.get_current_version()
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/lib/version.py", line 59, in get_current_version
    logging.info('Version: current_version = %s', current_version)
UnboundLocalError: local variable 'current_version' referenced before assignment
```
Thanks for any assistance.

**Comment by CMiksche** [comment]
I am not familiar with TurnKey Linux. From what I saw on the TurnKey Linux page it sounds like Gitea would run inside a virtual machine.

That would mean that this script should also be installed inside this virtual machine. Maybe you try to run this script outside of the virtual machine and that's causing the issue?

Also the `/home/git/: Permission denied`: The user which runs this script needs the access rights to the directory where Gitea is installed

**Comment by BadCo-NZ** [comment]
Hi @CMiksche, thanks for replying!

> I am not familiar with TurnKey Linux. From what I saw on the TurnKey Linux page it sounds like Gitea would run inside a virtual machine.

It is a Linux Container.

> That would mean that this script should also be installed inside this virtual machine. Maybe you try to run this script outside of the virtual machine and that's causing the issue?

Nope, I ran it inside the same container as gitea.

> Also the `/home/git/: Permission denied`: The user which runs this script needs the access rights to the directory where Gitea is installed

Good spotting, I didn't notice that. I have then tried to change user to git and re-execute the command and got a different error.

```shell
root@gitea ~# su git
$ gitea-auto-update --settings=/home/git/update/settings.ini
Traceback (most recent call last):
  File "/usr/local/bin/gitea-auto-update", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/update.py", line 90, in main
    fire.Fire(updater)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/update.py", line 81, in updater
    logging.basicConfig(filename=config.get('Gitea', 'logFile'), level=logging.DEBUG)
  File "/usr/lib/python3.7/logging/__init__.py", line 1900, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/root/update.log'
```
I then tried to change the log location to git user home directory:
```shell
root@gitea ~# su git
$ gitea-auto-update --settings=/home/git/update/settings.ini
Traceback (most recent call last):
  File "/usr/local/bin/gitea-auto-update", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/update.py", line 90, in main
    fire.Fire(updater)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/update.py", line 81, in updater
    logging.basicConfig(filename=config.get('Gitea', 'logFile'), level=logging.DEBUG)
  File "/usr/lib/python3.7/logging/__init__.py", line 1900, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/git/update/update.log'
```
I then manually created the log file, realised the folder /home/git/update had the wrong ownership, so chown'd them to git:git.
```shell
root@gitea ~# ls -l /home/git/
total 197253
drwxr-xr-x  2 root root         4 Jun  4 12:05 update
```
```shell
root@gitea ~# chown -R git:git /home/git/update/
```
```shell
root@gitea ~# ls -l /home/git/
total 197253
drwxr-xr-x  2 git  git          4 Jun  4 12:05 update
```
```shell
root@gitea ~# su git
$ gitea-auto-update --settings=/home/git/update/settings.ini
/bin/sh: 1: /home/git/: Permission denied
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/lib/version.py", line 48, in get_current_version
    current_version = self.get_version_from_file()
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/lib/version.py", line 42, in get_version_from_file
    return parse_file_version(version_string)
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/lib/version.py", line 24, in parse_file_version
    return string.split(" ")[2]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gitea-auto-update", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/update.py", line 90, in main
    fire.Fire(updater)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/update.py", line 83, in updater
    Update(config)
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/update.py", line 35, in __init__
    self.check_and_update()
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/update.py", line 62, in check_and_update
    current_version = version.get_current_version()
  File "/usr/local/lib/python3.7/dist-packages/gitea_auto_update/lib/version.py", line 59, in get_current_version
    logging.info('Version: current_version = %s', current_version)
UnboundLocalError: local variable 'current_version' referenced before assignment
```
And now I am stuck! Any other ideas?

**Comment by CMiksche** [comment]
>  ```shell
> UnboundLocalError: local variable 'current_version' referenced before assignment
> ```

That sounds like the script is unable to get the current version. Could you post your config file?

It sounds to me that either `site=` is set to a website which can't be accessed and / or `file=` is set to a file which can't be accessed.

Normally it still should work if the file path is set to the right path to the Gitea binary file. The `site=` setting is not necessary when the `file=` is correct.

**Comment by BadCo-NZ** [comment]
Sorry I should have previously posted it.
```bash
root@gitea ~# cat /home/git/update/settings.ini 
[Gitea]
site=https://gitea.lan.hardnet.nz/api/v1/version
apiUrl=https://api.github.com/repos/go-gitea/gitea/releases/latest
system=linux-amd64
file=/home/git/
tmpDir=/tmp/
buildFromSource=
sourceDir=
logFile=/home/git/update/update.log
```
![image](https://user-images.githubusercontent.com/50016048/174287814-04613cce-5800-48b0-886a-ec7fc4e8dd74.png)

```shell
root@gitea ~# ls -la /home/git/
total 197275
drwxr-xr-x  9 git  git         13 May 22 11:01 .
drwxr-xr-x  3 root root         3 Feb 12  2021 ..
-rw-r--r--  1 git  git        162 Feb 12  2021 .gitconfig
drwx------  2 git  git          7 Mar 21 01:58 .ssh
drwxr-xr-x  4 git  git          4 Feb 12  2021 custom
drwxr-xr-x 12 git  git         12 May  9 23:52 data
-rwxr-xr-x  1 git  git  107213392 Mar 20 22:27 gitea
-rwxr-xr-x  1 git  git  106436008 Dec 21 04:19 gitea-1.15.8
-rwxr-xr-x  1 git  git  115865232 Feb  2  2021 gitea-old
drwxr-xr-x  3 git  git          3 Oct 28  2021 gitea-repositories
drwxr-xr-x  2 git  git          2 Feb 12  2021 log
drwxr-xr-x  2 git  git          3 May  8 22:49 run
drwxr-xr-x  2 git  git          4 Jun  4 12:05 update
```

**Comment by CMiksche** [comment]
> ```shell
> file=/home/git/
> ```

Can u change this line to `/home/git/gitea` and test it again?

**Comment by BadCo-NZ** [comment]
Well that did something. The command ran and nothing visually happened in the terminal.
```bash
root@gitea ~# cat /home/git/update/update.log 
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/go-gitea/gitea/releases/latest HTTP/1.1" 200 None
INFO:root:Version: github_version_tag = v1.16.8
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/go-gitea/gitea/releases/latest HTTP/1.1" 200 None
INFO:root:Version: github_version_tag = v1.16.8
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/go-gitea/gitea/releases/latest HTTP/1.1" 200 None
INFO:root:Version: github_version_tag = v1.16.8
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/go-gitea/gitea/releases/latest HTTP/1.1" 200 None
INFO:root:Version: github_version_tag = v1.16.8
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/go-gitea/gitea/releases/latest HTTP/1.1" 200 None
INFO:root:Version: github_version_tag = v1.16.8
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/go-gitea/gitea/releases/latest HTTP/1.1" 200 None
INFO:root:Version: github_version_tag = v1.16.8
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/go-gitea/gitea/releases/latest HTTP/1.1" 200 None
INFO:root:Version: github_version_tag = v1.16.8
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/go-gitea/gitea/releases/latest HTTP/1.1" 200 None
INFO:root:Version: github_version_tag = v1.16.8
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/go-gitea/gitea/releases/latest HTTP/1.1" 200 None
INFO:root:Version: github_version_tag = v1.16.8
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/go-gitea/gitea/releases/latest HTTP/1.1" 200 5159
INFO:root:Version: github_version_tag = v1.16.8
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/go-gitea/gitea/releases/latest HTTP/1.1" 200 None
INFO:root:Version: github_version_tag = v1.16.8
INFO:root:Version: current_version = 1.16.4
INFO:root:Update: new version available, stopping service
ERROR:root:Download: missing dependency: xz
```
Looks like I am missing python-xz maybe?

**Comment by CMiksche** [comment]
> Looks like I am missing python-xz maybe?

Seems like we have another undocumented dependency.... But it's not python-xz, its `xz` directly (`xz` comes bundled with most linux distros but seems like Turnkey Linux really keeps it minimal...)

Try `sudo apt install xz-utils` and then run the script again.

**Comment by BadCo-NZ** [comment]
Nevermind, it was xz-utils that I was missing.

EDIT: Snap! That did the trick, update ran with success!

Thanks @CMiksche for taking the time to troubleshoot :)

**Comment by CMiksche** [comment]
Thank you too @BadCo-NZ - I just updated the new dependency section of this project and added xz-utils as a dependency ;-)
